# Site
name: 'DataBlow'
description: 'Um blog para falar de dados'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
url: 'http://www.adrianoavelar.com'
baseurl: ''
disqus: 'demowebsite'
email: 'eam.avelar@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    adriano:
      name:           Adriano
      site:           https://adrianoavelar.com.br
      avatar:         assets/images/avatar1.jpg
      bio:            "Olá, me chamo Adriano Avelar, criador do blog DataBox, que é um espaço "
      email:          eam.avelar@gmail.com
      twitter:        https://twitter.com/AdrianoAvelar14
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: adriano
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]